### ISSUE TITLE
AttributeError: 'gi._gi.GProps' object has no attribute 'bytes_per_file'

### ISSUE THREAD

**Issue by tiagocoutinho** [ufo-kit/tofu#86]
[plastified_rat__018_0000.edf.tar.gz](https://github.com/ufo-kit/tofu/files/3436106/plastified_rat__018_0000.edf.tar.gz)

Hi,
I a am tofu & ufo newbie.

I installed on a docker debian 10 image the ufo packages. 
I also installed tofu from latest github master.
I have some EDF files from a tomography like the one I send in attachment.
I try to run a tomography from the same directory where my EDF files are stored I get:

```
tofu tomo --width 2048 --height 211
Traceback (most recent call last):
  File "/usr/local/bin/tofu", line 216, in <module>
    main()
  File "/usr/local/bin/tofu", line 209, in main
    args._func(args)
  File "/usr/local/bin/tofu", line 27, in run_tomo
    reco.tomo(args)
  File "/usr/local/lib/python2.7/dist-packages/tofu/reco.py", line 78, in tomo
    writer = get_writer(params)
  File "/usr/local/lib/python2.7/dist-packages/tofu/tasks.py", line 36, in get_writer
    writer.props.bytes_per_file = params.output_bytes_per_file
AttributeError: 'gi._gi.GProps' object has no attribute 'bytes_per_file'
```
I get a similar error in a dialog box if I try the same with the `tofu gui`

Am I doing something wrong?

Here are the steps to have a docker image:
```
docker pull debian:buster
docker run -it debian:buster`  # here you must mount a volume where the EDF files are stored
apt update
apt install -y libufo-bin libufo-dev ufo-filters
apt install -y python-pip

# for the file reader
pip install fabio

apt install git
pip install git+https://github.com/ufo-kit/tofu
```

**Comment by tfarago** [comment]
You are doing nothing wrong. Tofu reflects the newest features of ufo-filters, which haven't made it to the repository yet. I added a fix, so when you pull tofu it should work now.

**Comment by tiagocoutinho** [comment]
Great, thanks! I will give it a try

**Comment by tiagocoutinho** [comment]
I advanced a little bit more but now I get another error:
```
$ tofu tomo --width 2048 --height 211
ERROR: ufo-resource-resources-error-quark: OpenCL Error: CL_DEVICE_NOT_FOUND (0)
```

Don't know if it helps, but here is the result of running `sudo lshw -json` on my machine:
https://pastebin.com/MH7ZkLFj

**Comment by tfarago** [comment]
Can you run `G_MESSAGES_DEBUG=all ufo-launch dummy-data width=128 height=128 number=1 ! null`

**Comment by tiagocoutinho** [comment]
Sure, here is the result:
```
(ufo-launch:28885): Ufo-DEBUG: 12:50:16.088: OPEN /usr/lib/x86_64-linux-gnu/ufo/libufofilterdummydata.so
(ufo-launch:28885): Ufo-DEBUG: 12:50:16.089: NEW  dummy-data-0x55586f40a1c0
(ufo-launch:28885): Ufo-DEBUG: 12:50:16.091: OPEN /usr/lib/x86_64-linux-gnu/ufo/libufofilternull.so
(ufo-launch:28885): Ufo-DEBUG: 12:50:16.091: NEW  null-0x55586f41c1e0
(ufo-launch:28885): Ufo-DEBUG: 12:50:16.092: CONN dummy-data-0x55586f40a1c0 -> null-0x55586f41c1e0 [input=0]
(ufo-launch:28885): Ufo-DEBUG: 12:50:16.127: INFO found 1 OpenCL platforms -1
(ufo-launch:28885): Ufo-DEBUG: 12:50:16.133: INFO Using CPUs=n GPUs=y Accelerators=n
Error executing pipeline: OpenCL Error: CL_DEVICE_NOT_FOUND
```

**Comment by tfarago** [comment]
Can you try to run any OpenCL code to make sure it's not UFO? What OpenCL platform are you using?

**Comment by tiagocoutinho** [comment]
I tried running `python dump-performance.py` from [pyopengl examples](https://github.com/inducer/pyopencl/tree/master/examples) and I get:
```
$ python dump-performance.py 
command latency: 1.76445e-05 s
profiling overhead: 8.80286e-07 s -> 5.0 %
empty kernel: 1.37194e-05 s
16 1228739.6514 0
32 2275301.5571 0
64 5056724.99036 0
128 7864530.00561 0
256 19339784.6873 0
512 39100086.1927 0
1024 77052621.4276 0
2048 153291604.78 0
4096 269076615.122 0
8192 626217788.655 0
16384 1234752528.82 0
32768 2277780358.68 0
65536 4978164461.18 0
131072 9350383772.23 0
262144 13681846037.6 0
524288 35266631506.8 0
1048576 76702448895.2 0
2097152 1.16678643717e+11 0
4194304 2.58712779581e+11 0
8388608 4.25651731053e+11 0
16777216 7.01324853676e+11 0
33554432 7.27112976887e+11 0
float32 add: 363556 GOps/s
----------------------------------------
HostToDeviceTransfer
----------------------------------------
latency: 2.69509e-05 s
bandwidth @ 64 bytes: 0.00233643 GB/s
bandwidth @ 256 bytes: 0.0081812 GB/s
bandwidth @ 1024 bytes: 0.0355205 GB/s
bandwidth @ 4096 bytes: 0.155211 GB/s
bandwidth @ 16384 bytes: 0.531958 GB/s
bandwidth @ 65536 bytes: 2.27542 GB/s
bandwidth @ 262144 bytes: 6.87067 GB/s
bandwidth @ 1048576 bytes: 9.81674 GB/s
bandwidth @ 4194304 bytes: 11.5647 GB/s
bandwidth @ 16777216 bytes: 13.9509 GB/s
bandwidth @ 67108864 bytes: 10.0791 GB/s
bandwidth @ 268435456 bytes: 13.6801 GB/s
bandwidth @ 1073741824 bytes: 14.3252 GB/s
----------------------------------------
DeviceToHostTransfer
----------------------------------------
latency: 2.62533e-05 s
bandwidth @ 64 bytes: 0.00224565 GB/s
bandwidth @ 256 bytes: 0.00948369 GB/s
bandwidth @ 1024 bytes: 0.0388744 GB/s
bandwidth @ 4096 bytes: 0.124277 GB/s
bandwidth @ 16384 bytes: 0.513203 GB/s
bandwidth @ 65536 bytes: 1.93861 GB/s
bandwidth @ 262144 bytes: 7.06384 GB/s
bandwidth @ 1048576 bytes: 11.7372 GB/s
bandwidth @ 4194304 bytes: 10.4229 GB/s
bandwidth @ 16777216 bytes: 8.85131 GB/s
bandwidth @ 67108864 bytes: 8.50939 GB/s
bandwidth @ 268435456 bytes: 13.6294 GB/s
bandwidth @ 1073741824 bytes: 13.4952 GB/s
----------------------------------------
DeviceToDeviceTransfer
----------------------------------------
latency: 2.07105e-05 s
bandwidth @ 64 bytes: 0.00197192 GB/s
bandwidth @ 256 bytes: 0.0116702 GB/s
bandwidth @ 1024 bytes: 0.0572127 GB/s
bandwidth @ 4096 bytes: 0.120947 GB/s
bandwidth @ 16384 bytes: 0.870225 GB/s
bandwidth @ 65536 bytes: 3.78345 GB/s
bandwidth @ 262144 bytes: 15.0242 GB/s
bandwidth @ 1048576 bytes: 14.9859 GB/s
bandwidth @ 4194304 bytes: 14.1709 GB/s
bandwidth @ 16777216 bytes: 9.41001 GB/s
bandwidth @ 67108864 bytes: 14.4381 GB/s
bandwidth @ 268435456 bytes: 14.3696 GB/s
bandwidth @ 1073741824 bytes: 13.1971 GB/s
```

**Comment by tfarago** [comment]
That's strange. Could you try to install from sources and take a look at what cmake or meson say about OpenCL?
